In [1]:
from sklearn import svm , datasets
iris = datasets.load_iris()
import pandas as pd
import numpy as np

In [2]:
data,target = datasets.load_iris(return_X_y=True)
df = pd.DataFrame(iris.data , columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [3]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,  y_train , y_test = train_test_split(iris.data , iris.target , test_size = 0.3) 

In [4]:
model = svm.SVC(kernel='rbf' , C=30 , gamma = 'auto')
model.fit(X_train , y_train)
model.score(X_test , y_test)

0.9111111111111111

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
# method - 1 checking one by one
cross_val_score (svm.SVC(kernel = 'linear' , C=10 , gamma = 'auto') , iris.data , iris.target , cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [7]:
cross_val_score (svm.SVC(kernel = 'rbf' , C=10 , gamma = 'auto') , iris.data , iris.target , cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score (svm.SVC(kernel = 'rbf' , C=20 , gamma = 'auto') , iris.data , iris.target , cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [10]:
# method - 2 using for loop
kernels = ['rbf' , 'linear']
C = [1 ,10 ,20]
avg_scores  = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score (svm.SVC(kernel = kval , C=cval , gamma = 'auto') , iris.data , iris.target , cv = 5)
        avg_scores[kval+ '_' + str(cval)] = np.average(cv_scores)
avg_scores        

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [13]:
# methos- 3 using grid search cv
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma = 'auto') , {
    'C' : [1,10,20],
    'kernel' : ['rbf' , 'linear']
} , cv = 5 , return_train_score=False)
clf.fit(iris.data , iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00120559, 0.00060115, 0.00059552, 0.00060768, 0.00079522,
        0.00051703]),
 'std_fit_time': array([0.0004015 , 0.00049088, 0.00048628, 0.00049639, 0.00039767,
        0.00046086]),
 'mean_score_time': array([0.00121536, 0.00039644, 0.00060282, 0.00059962, 0.00040078,
        0.00039425]),
 'std_score_time': array([0.00038584, 0.00048556, 0.0004922 , 0.0004896 , 0.00049086,
        0.00048286]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [14]:
# importing above data in panda dataframe
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C   
0       0.001206      0.000402         0.001215        0.000386       1  \
1       0.000601      0.000491         0.000396        0.000486       1   
2       0.000596      0.000486         0.000603        0.000492      10   
3       0.000608      0.000496         0.000600        0.000490      10   
4       0.000795      0.000398         0.000401        0.000491      20   
5       0.000517      0.000461         0.000394        0.000483      20   

  param_kernel                         params  split0_test_score   
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667  \
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score   
0                1.0           0.966667           0.966667                1.0  \
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [16]:
df[['param_C' , 'param_kernel' , 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667